version: CI-{build}
image: Visual Studio 2019
skip_non_tags: true
clone_script:
- cmd: git clone --recursive https://github.com/Sewer56/Riders.Tweakbox.git

init:
- ps: |-
    # Install the Tools
    & choco upgrade chocolatey
    & choco install reloaded-ii-tools --version=1.0.0 -y
    
    # Update Build Version
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
    }
build_script:
- ps: |-
    cd Riders.Tweakbox

    # Build the Changelog
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        $env:CHANGELOG_PATH = "CHANGELOG.MD"
        & npm install -g auto-changelog
        & auto-changelog --sort-commits date --hide-credit --template changelog-template.hbs --commit-limit false --starting-version $env:APPVEYOR_REPO_TAG_NAME -o $env:CHANGELOG_PATH 
        $env:CHANGELOG_TEXT = Get-Content -Path $env:CHANGELOG_PATH -Raw
    }
    # Build The Mod(s)
    & ./Publish.ps1
    # Create NuGet Packages
    $publishDirectory = "./Publish"
    $allZips = Get-ChildItem $publishDirectory -Filter *.zip
    foreach ($publishFile in $allZips) 
    {
        $nupkgName = [System.IO.Path]::ChangeExtension($publishFile.FullName, ".nupkg")
        $fullZipPath = $publishFile.FullName
        NuGetConverter.exe "$fullZipPath" "$nupkgName"
    }

artifacts:
- path: ./Riders.Tweakbox/Publish/*.zip
  name: Compiled Mod(s)
- path: ./Riders.Tweakbox/Publish/*.nupkg
  name: Compiled NuGet Packages
deploy:
- provider: GitHub
  description: $(CHANGELOG_TEXT)
  auth_token:
    secure: 3nktB3Ovacl0onzwjgI+F7MtWvAzl1YMIA5gRE+vsVwKzFHICg1wKlj9O63IIiwS
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
