site_name: Riders.Tweakbox Documentation
site_url: http://sewer56.dev/Riders.Tweakbox/

repo_name: Reloaded-Project/Riders.Tweakbox
repo_url: https://github.com/Reloaded-Project/Riders.Tweakbox

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sewer56
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheSewer56

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

theme:
  name: material
  palette:
    primary: red
    accent: red
    scheme: slate
    
pages:
  - Home: index.md
  - Features: features.md
  - Installation: installation.md
  - Reporting Issues: reporting-issues.md
  - Building: building.md
  - Customization: 
    - Music: custom-music.md
    - Textures: textures.md
    - Optimizing Textures: optimizing-textures.md
    - Animated Textures: animated-textures.md
    
  - Changelog:
    - 0.5.0:  Changelogs/0.5.0/0.5.0.md
    - 0.4.0:  Changelogs/0.4.0/0.4.0.md
    - 0.3.1:  Changelogs/0.3.1/0.3.1.md