using System;
using MessagePack;
using Reloaded.Memory;
using Riders.Netplay.Messages.Reliable.Structs.Menu.Shared;
using Sewer56.SonicRiders.Structures.Menus.Enums;

namespace Riders.Netplay.Messages.Reliable.Structs.Menu.Commands
{
    /// <summary>
    /// Client -> Host
    /// </summary>
    [MessagePackObject()]
    public struct CharaSelectLoop : IMenuSynchronizationCommand, IEquatable<CharaSelectLoop>
    {
        public Shared.MenuSynchronizationCommand GetCommandKind() => Shared.MenuSynchronizationCommand.CharaSelectLoop;
        public byte[] ToBytes() => Struct.GetBytes(this);

        /// <summary>
        /// The character selected by the current player.
        /// </summary>
        [Key(0)]
        public byte Character;

        /// <summary>
        /// Current board selected by the player.
        /// </summary>
        [Key(1)]
        public byte Board;

        /// <summary>
        /// Current status of the player.
        /// </summary>
        [Key(2)]
        public PlayerStatus Status;

        public CharaSelectLoop(byte character, byte board, PlayerStatus status)
        {
            Character = character;
            Board = board;
            Status = status;
        }

        #region Autogenerated
        public bool Equals(CharaSelectLoop other)
        {
            return Character == other.Character && Board == other.Board && Status == other.Status;
        }

        public override bool Equals(object obj)
        {
            return obj is CharaSelectLoop other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hashCode = Character.GetHashCode();
                hashCode = (hashCode * 397) ^ Board.GetHashCode();
                hashCode = (hashCode * 397) ^ (int)Status;
                return hashCode;
            }
        }
        #endregion
    }
}